AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Lint/ToJSON:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 45
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/BlockLength:
  Max: 130
Metrics/ClassLength:
  Max: 600
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 45
Metrics/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
