assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
  id_rsa: zerocracy/home#assets/heroku-key
  id_rsa.pub: zerocracy/home#assets/heroku-key.pub
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo apt-get -y update
  sudo apt-get -y install libcurl4-openssl-dev
  sudo gem install pdd
release:
  script: |-
    export RUBYOPT="-W0"
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/zold/version.rb
    bundle install --no-color
    rake --quiet
    git add lib/zold/version.rb
    git commit -m "version set to ${tag}"
    gem build zold.gemspec
    gem install ./zold-0.0.0.gem
    zold --version | grep -vq '0.0.0' && exit 1
    zold remote update
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    git remote add heroku git@heroku.com:zold.git
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    sed -i -s 's|Gemfile.lock||g' .gitignore
    bundle update
    trap 'git reset HEAD~1' EXIT
    git add Gemfile.lock
    git add .gitignore
    git fetch
    git commit -m 'config' && git push -f heroku $(git symbolic-ref --short HEAD):master
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://b1.zold.io > /dev/null
architect:
- yegor256
merge:
  script: |-
    bundle install
    rake --quiet
    pdd -f /dev/null -v
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
