# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
architect:
  - yegor256
  - davvd
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
  docker-password: yegor256/home#assets/docker-password
install: |
  pdd -f /dev/null -v
  sudo apt-get -y update
  sudo apt-get install --yes libcurl4-openssl-dev
  bundle update --no-color
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    export RUBYOPT="-W0"
    sed -i "s/0\.0\.0/${tag}/g" lib/zold/version.rb
    bundle exec rake --quiet
    git add lib/zold/version.rb
    git commit -m "version set to ${tag}"
    gem build zold.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml

    sed -i -e "s/0.0.0/${tag}/" Dockerfile
    git add Dockerfile
    git commit -m "version set to ${tag}"
    repo=yegor256/zold
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker build "$(pwd)" --tag "${repo}:latest"
    cat ../docker-password | sudo docker login --password-stdin -u yegor256
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
merge:
  script: |-
    bundle exec rake --quiet
